schema_version: 1

context:
  name: bokeh-django
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/bokeh/bokeh-django/archive/v${{ version }}.tar.gz
  sha256: 9fc18ca011cfb4b0b58cbff93fce8e40ca72ff16e428b210b9637b45c8ccef56

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - bokeh
    - django
    - channels

tests:
  - python:
      imports:
        - bokeh_django
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Utility to integrate Bokeh with Django Channels
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/bokeh/bokeh-django

extra:
  recipe-maintainers:
    - rxm7706
